### ISSUE TITLE
go.mod contains no "/v2" suffix for version 2.0.0?

### ISSUE THREAD

**Issue by fd0** [zchee/color#1]
Hey,

I'm working on a an introduction to Go Modules and took your fork of fatih's color library as an example. I saw you made a 2.0.0 release yesterday, but the module path `go.mod` is still `github.com/zchee/color`, so I'm unable to use it:
```
$ go version
go version go1.12.5 linux/amd64

$ go list -m -versions github.com/zchee/color
github.com/zchee/color v0.2.0 v1.0.0 v1.1.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0 v1.6.0 v1.7.0

$ go get github.com/zchee/color@v2
go get github.com/zchee/color@v2: no matching versions for query "v2"

$ go get github.com/zchee/color/v2                                                                                                      go: finding github.com/zchee/color/v2 v2.0.0
go: github.com/zchee/color/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/zchee/color" (and .../v2/go.mod does not exist) at revision v2.0.0
go: error loading module requirements
```

I think you need to set the module path (first line in `go.mod`) to `github.com/zchee/color/v2` for version 2.0.0 and later. Is that right? I must admit I haven't released a library with a version later than 1.0.0 yet...

I would suggest releasing 2.0.1 with the changed `go.mod`, that should probably do the trick :)

Thanks!

**Comment by zchee** [comment]
@fd0 Ah, sorry for the late reply and confusing you.

First, I was mistaken to tagged `v2`, but the correct tag name is `v2.0.0`. So I was removed `v2` and re-tagged `v2.0.0`. (but maybe not related to this issue I think)

---

OK, back to the main topic.

> I think you need to set the module path (first line in go.mod) to github.com/zchee/color/v2 for version 2.0.0 and later. 

I didn't understand all yet to Go module spec, But you're right, I think probably best practice is to change `github.com/zchee/color/v2` if I released `v2.x.x`.

<blockquote>

```console
$ go list -m -versions github.com/zchee/color
github.com/zchee/color v0.2.0 v1.0.0 v1.1.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0 v1.6.0 v1.7.0
```

</blockquote>

I'm surprised :O and don't understand yet why not listed `v2.0.0` tag, also even if add `-u` flag. (I'll digging Go core code, thanks for the give killing time topic. lol)
However, As you said, I should edit `go.mod` file and release new `v2.0.1` tag.

For my future knowledge and just in case, I'll try to create a pseudo-package repository, released some tags, and checks whether the show each tag with `go list -u -m -versions ...` command correctly.

---

Thank you for posting this issue! And sorry for bad English (I'm Japanese)
I'll close this issue when I release the next tag.

**Comment by zchee** [comment]
Close via https://github.com/zchee/color/commit/e6dbfcec5a6a3f0264f3715f1c1a7c930fcb1c83

**Comment by fd0** [comment]
Awesome, thanks for taking care of this issue!

> ```
> $ go list -m -versions github.com/zchee/color
> github.com/zchee/color v0.2.0 v1.0.0 v1.1.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0 v1.6.0 v1.7.0
> ```
>
> I'm surprised :O and don't understand yet why not listed v2.0.0 tag, also even if add -u flag.

I can explain that: Go Modules enforce a rule called Semantic Import Versioning. Strictly speaking, a new major version of a library is considered a different library. In order to fit this nicely into the Go ecosystem, the import path needs to have the major version suffix after `2.0.0`. So `github.com/zchee/color` is considered a different library than `github.com/zchee/color`.

If you want to see the available versions for this library, you need to specify the import path for it:
```
$ go list -m versions github.com/zchee/color/v2
go: finding github.com/zchee/color/v2 v2.0.3
github.com/zchee/color/v2 v2.0.0 v2.0.1 v2.0.2 v2.0.3
```

You can even import both libraries into the same project, although you need to locally rename one of the libraries because they both call themselves `color` (which is fine):

```
$ cat main.go
package main

import (
	"github.com/zchee/color"
	colorv2 "github.com/zchee/color/v2"
)

func main() {
	// uses color v1.X
	color.New(color.FgCyan).Add(color.Underline).Println("Hello Gophers!")

	// uses color v2.X
	colorv2.New(colorv2.FgCyan).Add(colorv2.Underline).Println("Hello Gophers!")
}

$ cat go.mod
module github.com/fd0/demo2

go 1.12

require (
	github.com/zchee/color v1.7.0
	github.com/zchee/color/v2 v2.0.3
)

$ go run .
Hello Gophers!
Hello Gophers!
```

I hope this helps understanding Go Modules a bit better (I'm also still getting used to it!)
